name: PlayerCountPlus
description: A Pluing thats allow you to set the player count
main: com.diphioc.playercoutplus.PlayerCountplus
version: 1.0
authors: [Diphioc]
commands:
  pc:
    description: PlayerCount command
    permission: playercountplus.command.pc
